package com.basket.core.common.designSystem.compose.theme

import androidx.compose.ui.graphics.Color

object ColorPalette {
    // val PrimaryColor = Color(0xFFFF4747)
    val PrimaryColor = Color(0xFF2C3D5B)
    val PrimaryVariantColor = Color(0xFFCA3D49)
    val AccentColor = Color(0xFFC62F79)
    val BackgroundContent = Color(0xFFf6f6f6)
    val lightSurface = Color(0xFFf5f5f5)
    val White = Color(0xFFFFFFFF)
    val Surface = Color(0xFFF7F7F7)
    val BoxGrey10 = Color(0x1A828282)
    val BoxGrey = Color(0xFFE4E4E4)
    val MarineBlue = Color(0xFF0172D5)
    val DeepSkyeBlue = Color(0xFF007eff)
    val SkyeBlue = Color(0xFF00B2FF)
    val MidBlue100 = Color(0xFF278997)
    val Error = Color(0xFFFF0000)
    val ErrorLight = Color(0xFFFA7676)
    val LightBlue = Color(0xff278997)
    val LightGrey = Color(0x66000000)
    val LightGreyDisabled = Color(0x99000000)
    val LightGrey2 = Color(0xFFF1F1F1)
    val LightGrey3 = Color(0x99B4B1B1)
    val NavyBlue = Color(0xFF1F487E)
    val NavyBlueLight = Color(0xFFF5F8FE)
    val FilterChipSelected = Color(0xFF34A4FF)
    val FilterChipBase = Color(0xFFEDEDED)
    val MaxBlueGreen = Color(0xFF33BDD1)
    val Orange = Color(0xFFFF8A00)
    val VioletPink = Color(0xFFEF60FF)
    val DarkMagenta = Color(0xFF780f81)
    val LimeGreen = Color(0xFF4B9E12)
    val TealishBlue = Color(0xFF76ADFF)
    val Black = Color(0xFF000000)
    val Azure = Color(0xFF007FFF)

    val Grey = Color(0xFF404649)

    val PagerDotColor = Color(0xFFC4CDD3)
    val IconColorGrey = Grey

    val TextFieldColor = Color(0xFFf6f6f6)
    val BorderColor = Color(0xFFDBDBDC)

    val splashBackground = Color(0xFF272320)

    val grey_050 = Color(0xFFfafafa) // Use with black text
    val grey_700 = Color(0xFF616161) // Use with white text

    val orange_400 = Color(0xFFffa726) // Use with black text

    val blue900 = Color(0xFF1c1c59)
    val blue400 = Color(0xFF4b4387)
    val blueDark = Color(0xFF000030)

    val petrol800 = Color(0xFF007884)

    val Yellow400 = Color(0xFFF6E547)
    val Yellow600 = Color(0xFFF5CF1B)
    val Yellow700 = Color(0xFFF3B711)
    val Yellow800 = Color(0xFFF29F05)

    /* val Blue200 = Color(0xFF9DA3FA)
     val Blue400 = Color(0xFF4860F7)
     val Blue500 = Color(0xFF0540F2)
     val Blue800 = Color(0xFF001CCF)*/

    val Red300 = Color(0xFFEA6D7E)
    val Red800 = Color(0xFFD00036)
}

val BlueGradientColors =
    listOf(
        Color(0xFF36bdd1),
        Color(0xFF2fa6b7),
        Color(0xFF2498a9),
        Color(0xFF2a909f),
        Color(0xFF2c8b99),
        Color(0xFF258897),
    )

val GreyGradientColors =
    listOf(
        Color(0x66000000),
        Color(0x66000000),
    )

// Generated by https://m3.material.io/theme-builder#/dynamic

/*@OptIn(ExperimentalStdlibApi::class)
fun colorFromHex(hexColor: String): Color {
    return when {
        hexColor.startsWith("#") -> {
            Color(android.graphics.Color.parseColor(hexColor))
 */
/*when (hexColor.length) {
                in 0..7 -> hexColor.padStart(length = 1, padChar = '#')
                else -> hexColor.replaceFirst(oldValue = "#", newValue = "0x")
                // TODO make else better because there could be more option for color pattern
                // THIS COULD BE A PROBLEM "#FF0172D5"
            }*/
/*
        }

        else -> {
            if (hexColor.length <= 6) {
                Color(android.graphics.Color.parseColor("#$hexColor"))
            } else {
                Color(hexColor.hexToLong())
            }
        }
    }
}*/
